export const SAGA_LOAD_PRODUCTS = 'SAGA_LOAD_PRODUCTS'


export const SAGA_ADD_CATEGORY = 'SAGA_ADD_CATEGORY'
export const SAGA_REMOVE_CATEGORY = 'SAGA_REMOVE_CATEGORY'

export const SAGA_ADD_ITEM_CART = 'SAGA_ADD_ITEM_CART'
export const SAGA_REMOVE_ITEM_CART = 'SAGA_REMOVE_ITEM_CART'
export const SAGA_UPDATE_ITEM_CART = 'SAGA_UPDATE_ITEM_CART'
export const SAGA_FINISH_BUY = 'SAGA_FINISH_BUY'