export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'

export const ADD_ITEM_CART = 'ADD_ITEM_CART'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const UPDATE_ITEM_CART = 'UPDATE_ITEM_CART'
export const FINISH_BUY = 'FINISH_BUY'